#!/usr/bin/env python3
# Copyright (C) 2026, Arborisis — GPL-3.0-or-later
"""Copy MeshCore's companion radio into app/mcc/, renamed to live next to the repeater.

    python3 tools/import_companion.py [path-to-examples/companion_radio]

The MeshCore app talks to a *companion* (examples/companion_radio), not to a
repeater: over Bluetooth it looks for "MeshCore-…" and speaks the companion
frame protocol. Arborisis Mesh runs that companion in its `companion` mode,
on the same radio arbiter as everything else. Both MeshCore applications
are built into every image (the mode is chosen at boot), so the companion's
names that collide with the repeater's are renamed (MyMesh, NodePrefs…),
and a few lines are adapted:

- CompanionMesh.cpp includes McRedirect.h, as the repeater does: its
  `radio_driver` calls land on the arbiter's MeshCore port;
- on ESP32 the store uses LittleFS, not SPIFFS: the board's file system
  (app/ArbPlatform.h) — including for the app's "format" command, which
  would otherwise write a SPIFFS over it;
- the UI task interface does not pull in the buzzer driver: MeshCore's
  companion UIs are not built (app/ArbUI is the display);
- on nRF52 the store keeps everything on InternalFS: the Arborisis images
  link with the standard layout (tools/gen_envs.py), where the flash that
  MeshCore's companion gives to a second file system belongs to the
  application.

Only the files that make the companion are taken: its main.cpp and user
interfaces are replaced by app/main.cpp and app/ArbUI. Run by
tools/sync_meshcore.sh; nothing under app/mcc/ is edited by hand.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "examples" / "companion_radio"
DST = ROOT / "app" / "mcc"

FILES = {
    "MyMesh.h": "CompanionMesh.h",
    "MyMesh.cpp": "CompanionMesh.cpp",
    "DataStore.h": "CompanionStore.h",
    "DataStore.cpp": "CompanionStore.cpp",
    "NodePrefs.h": "CompanionNodePrefs.h",
    "AbstractUITask.h": "CompanionUITask.h",
}
# Whole words, longest first (DataStoreHost before DataStore).
RENAMES = [
    ("DataStoreHost", "CompanionStoreHost"),
    ("DataStore", "CompanionStore"),
    ("MyMesh", "CompanionMesh"),
    ("the_mesh", "companion_mesh"),
    ("NodePrefs", "CompanionNodePrefs"),
    ("AdvertPath", "CompanionAdvertPath"),
    ("AbstractUITask", "CompanionUITask"),
    ("UIEventType", "CompanionUIEvent"),
    # ESP32: the board's LittleFS (app/ArbPlatform.h), not SPIFFS.
    ("SPIFFSFS", "LittleFSFS"),
    ("SPIFFS", "LittleFS"),
]
HEADER = ("// GENERATED by tools/import_companion.py from MeshCore's examples/companion_radio/{src}\n"
          "// (MIT, see mesh/LICENSE-MeshCore.txt) — do not edit.\n")


def must_replace(s, old, new, what):
    assert old in s, f"{what}: `{old.strip()}` not found, update tools/import_companion.py"
    return s.replace(old, new, 1)


def main():
    DST.mkdir(parents=True, exist_ok=True)
    for old in DST.iterdir():
        old.unlink()
    for src, dst in FILES.items():
        s = (SRC / src).read_text()
        for a, b in RENAMES:
            s = re.sub(r"\b" + a + r"\b", b, s)
        if dst == "CompanionMesh.cpp":
            s = must_replace(s, '#include "CompanionMesh.h"\n',
                             '#include "CompanionMesh.h"\n'
                             '#include "McRedirect.h"   // Arborisis: radio_driver -> the arbiter\'s MeshCore port\n',
                             dst)
        if dst == "CompanionUITask.h":
            # The buzzer belongs to MeshCore's own UI tasks (ui-new/…), which
            # Arborisis does not build: its header needs a library the
            # repeater environments do not carry.
            s = must_replace(s, "#ifdef PIN_BUZZER\n  #include <helpers/ui/buzzer.h>\n#endif\n",
                             "// Arborisis: no buzzer include (MeshCore's UI tasks are not built).\n", dst)
        if dst == "CompanionStore.cpp":
            s = must_replace(s, '#include "CompanionStore.h"\n',
                             '#include "CompanionStore.h"\n'
                             '// Arborisis: one file system, the board\'s (standard nRF52 layout, no QSPI store).\n'
                             '#undef EXTRAFS\n#undef QSPIFLASH\n',
                             dst)
        (DST / dst).write_text(HEADER.format(src=src) + s)
    print(f"app/mcc refreshed from {SRC}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
